### ISSUE TITLE
Add dart icon

### ISSUE THREAD

**Issue by Sergio-P** [marlongerson/jetbrains-icons#1]
Thanks for the icons. I've been using it for a few days and they look fine. I wonder if you can add the dart icon. This icon comes from the dart plugin repositor and can be found here: https://github.com/JetBrains/intellij-plugins/blob/master/Dart/resources/icons/dart_file.svg

Thanks in advance

**Comment by marlongerson** [comment]
@Sergio-P Thanks for your request. Dart icon is added now.
